import fs from 'node:fs/promises';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { jarMetadata, digest } from '../jar-metadata.mjs';
import { verifyRelease } from '../verify-release.mjs';

const execute = promisify(execFile);
for (const dir of ['/home/yanus/app', '/home/yanus/incoming', '/etc/yanus-deploy', '/opt/yanus-observability', '/usr/local/lib/yanus-deploy', '/var/log/yanus/prod']) await fs.mkdir(dir, { recursive: true });
await fs.cp('/source/ops/deploy', '/usr/local/lib/yanus-deploy/deploy', { recursive: true });
await fs.cp('/source/ops/observability', '/usr/local/lib/yanus-deploy/observability', { recursive: true });
await fs.copyFile('/source/build/libs/attendance-0.0.1-SNAPSHOT.jar', '/home/yanus/app/app.jar');
await fs.copyFile('/source/ops/observability/application-observability.properties', '/opt/yanus-observability/application-observability.properties');
await fs.appendFile('/opt/yanus-observability/application-observability.properties', '\nmanagement.health.mail.enabled=false\n');
await execute('chown', ['-R', 'yanus:yanus', '/home/yanus', '/var/log/yanus']);
await execute('systemctl', ['start', 'postgresql']);
await execute('runuser', ['-u', 'postgres', '--', 'psql', '-v', 'ON_ERROR_STOP=1', '-c', "DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='yanus') THEN CREATE USER yanus WITH PASSWORD 'qa-only'; END IF; IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='root') THEN CREATE ROLE root LOGIN SUPERUSER; END IF; END $$;"]);
const { stdout: databases } = await execute('runuser', ['-u', 'postgres', '--', 'psql', '-XAt', '-c', "SELECT datname FROM pg_database WHERE datname='yanus'"]);
if (!databases.trim()) await execute('runuser', ['-u', 'postgres', '--', 'createdb', '-O', 'yanus', 'yanus']);
await fs.writeFile('/root/.pg_service.conf', '[yanus-deploy]\nhost=/var/run/postgresql\ndbname=yanus\nuser=root\n', { mode: 0o600 });
await fs.writeFile('/home/yanus/app/.env', 'DB_URL=jdbc:postgresql://127.0.0.1:5432/yanus\nDB_USERNAME=yanus\nDB_PASSWORD=qa-only\nJWT_SECRET=qa-test-secret-must-have-more-than-32-characters\nMINIO_ENDPOINT=http://127.0.0.1:9000\nMINIO_ACCESS_KEY=fixture\nMINIO_SECRET_KEY=fixture-only\nMAIL_USERNAME=fixture\nMAIL_PASSWORD=fixture-only\nSPRING_CONFIG_ADDITIONAL_LOCATION=file:/opt/yanus-observability/application-observability.properties\n', { mode: 0o600 });
await fs.writeFile('/etc/systemd/system/yanus.service', '[Unit]\nAfter=postgresql.service\n[Service]\nUser=yanus\nEnvironmentFile=/home/yanus/app/.env\nExecStart=/usr/bin/java -jar /home/yanus/app/app.jar\nRestart=no\n[Install]\nWantedBy=multi-user.target\n');
await execute('systemctl', ['daemon-reload']); await execute('systemctl', ['start', 'yanus']);
const metadata = await jarMetadata('/home/yanus/app/app.jar');
const ready = await verifyRelease({ management: 'http://127.0.0.1:9091', main: 'http://127.0.0.1:8080', commit: metadata.commit });
if (!ready.ok) throw new Error(`Fixture startup: ${ready.reason}`);
const { stdout } = await execute('psql', ['service=yanus-deploy', '-XAt', '-c', "SELECT coalesce(json_agg(t ORDER BY installed_rank),'[]'::json) FROM (SELECT installed_rank,version,script,checksum,type,success FROM flyway_schema_history ORDER BY installed_rank) t"]);
const baseline = { sha256: metadata.sha256, sourceCommit: metadata.commit, runningCommit: metadata.commit, schemaSha256: digest(JSON.stringify(JSON.parse(stdout))), compatibilityApproved: true, environment: 'qa', qaPublicUrl: 'http://127.0.0.1:8080/v3/api-docs' };
await fs.writeFile('/etc/yanus-deploy/baseline.json', JSON.stringify(baseline), { mode: 0o600 });
await fs.mkdir(`/home/yanus/incoming/${metadata.commit}`, { recursive: true });
await fs.copyFile('/home/yanus/app/app.jar', `/home/yanus/incoming/${metadata.commit}/app.jar`);
await execute('node', ['/usr/local/lib/yanus-deploy/deploy/create-manifest.mjs', `/home/yanus/incoming/${metadata.commit}/app.jar`, `/home/yanus/incoming/${metadata.commit}/manifest.json`], { env: { ...process.env, GITHUB_SHA: metadata.commit } });
console.log(JSON.stringify({ status: 'FIXTURE_READY', commit: metadata.commit, sha256: metadata.sha256, schema: metadata.migrations.length, systemd: true, production: false }));
