import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { randomBytes } from 'node:crypto';
import assert from 'node:assert/strict';

const execute = promisify(execFile);
const name = `yanus-backup-qa-${randomBytes(6).toString('hex')}`;
const image = 'yanus-backup-qa:212';
const run = async (...args) => execute('docker', args, { timeout: 180_000, maxBuffer: 2 * 1024 * 1024 });
const shell = async command => (await run('exec', name, 'bash', '-ceu', command)).stdout.trim();
const backup = '/usr/local/libexec/yanus-backup/backup.sh';
const gateway = '/usr/local/libexec/yanus-backup/transport.sh';
const config = '/etc/yanus-backup/config.json';
const receipts = [];

try {
  await run('build', '-f', 'ops/backup/qa/Dockerfile', '-t', image, '.');
  await run('run', '-d', '--name', name, '-e', 'POSTGRES_DB=yanus', '-e', 'POSTGRES_HOST_AUTH_METHOD=trust', image);
  await shell('for ((i=0;i<100;i++)); do pg_isready -h 127.0.0.1 -q && exit 0; sleep 0.2; done; exit 1');
  await shell(`install -d -m 0700 /etc/yanus-backup
age-keygen -o /tmp/qa-identity 2>/dev/null
jq -n --arg recipient "$(age-keygen -y /tmp/qa-identity)" '{database:"yanus",spool:"/var/backups/yanus-db",runtime:"/run/yanus-backup",state:"/var/lib/yanus-backup",metrics:"/var/lib/prometheus/node-exporter",recipient:$recipient,retention_days:14}' > ${config}
chmod 600 ${config}
runuser -u postgres -- psql -Xq -v ON_ERROR_STOP=1 -d yanus -c "CREATE TABLE flyway_schema_history(installed_rank int PRIMARY KEY,version text,success boolean); INSERT INTO flyway_schema_history VALUES(1,'1',true),(2,'2',true); CREATE TABLE qa_team(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name text NOT NULL); INSERT INTO qa_team(name) VALUES('fixture team'); CREATE TABLE qa_member(id bigint PRIMARY KEY,team_id bigint REFERENCES qa_team); INSERT INTO qa_member VALUES(10,1),(11,1);"
bash -n /usr/local/libexec/yanus-backup/*.sh`);
  const success = JSON.parse(await shell(backup));
  assert.equal(success.status, 'SUCCESS');
  const state = JSON.parse(await shell('cat /var/lib/yanus-backup/local.json'));
  const id = state.id;
  const lines = (await shell(`${gateway} list`)).split('\n');
  assert.equal(lines.length, 1, '전송 목록은 백업마다 JSON 한 줄을 반환해야 한다');
  const metadata = JSON.parse(lines[0]);
  assert.equal(metadata.id, id);
  await shell(`mkdir -m 700 /tmp/decrypted; age -d -i /tmp/qa-identity /var/backups/yanus-db/${id}.age | tar -xf - -C /tmp/decrypted`);
  const verification = JSON.parse(await shell('cat /tmp/decrypted/verification.json'));
  assert.equal(verification.tables.find(item => item.table === 'qa_member').rows, 2);
  assert.equal(verification.history.length, 2);
  assert.equal(verification.snapshot_epoch, metadata.snapshot_epoch);
  assert.match(await shell('cat /tmp/decrypted/roles.sql'), /CREATE ROLE postgres/);
  assert.doesNotMatch(await shell('cat /tmp/decrypted/roles.sql'), /PASSWORD/);
  receipts.push({ scenario: '실제 PG16 dump·동일 snapshot 건수·age 복호화', status: 'PASS' });

  await assert.rejects(shell(`flock /var/lib/yanus-backup/backup.lock ${backup}`), error => error.code === 75);
  assert.equal(JSON.parse(await shell('cat /var/lib/yanus-backup/local.json')).last_run_success, 1);
  receipts.push({ scenario: '중복 실행 차단·성공 상태 보존', status: 'PASS' });

  await shell(`jq '.database="missing_fixture"' ${config} > /etc/yanus-backup/failed.json; chmod 600 /etc/yanus-backup/failed.json`);
  await assert.rejects(shell(`${backup} /etc/yanus-backup/failed.json`));
  const failed = JSON.parse(await shell('cat /var/lib/yanus-backup/local.json'));
  assert.equal(failed.last_run_success, 0);
  assert.equal(failed.last_success_snapshot_epoch, state.last_success_snapshot_epoch);
  assert.equal(await shell('find /run/yanus-backup -mindepth 1 -maxdepth 1 -type d | wc -l'), '0');
  receipts.push({ scenario: 'DB 접근 실패·기존 archive 보존·임시 평문 정리', status: 'PASS' });

  const old = '20260101T000000Z-1111111111111111';
  const unacked = '20260101T000000Z-2222222222222222';
  await shell(`for clone in ${old} ${unacked}; do cp /var/backups/yanus-db/${id}.age /var/backups/yanus-db/$clone.age; jq --arg id "$clone" '.id=$id | .snapshot_epoch=1767225600' /var/backups/yanus-db/${id}.json > /var/backups/yanus-db/$clone.json; done; touch /var/backups/yanus-db/${old}.acked`);
  await shell(`${gateway} ack ${id} ${metadata.sha256}`);
  assert.equal(await shell(`test ! -f /var/backups/yanus-db/${old}.age && test -f /var/backups/yanus-db/${unacked}.age && test -f /var/backups/yanus-db/${id}.age && echo retained`), 'retained');
  await shell(`${gateway} ack ${unacked} ${metadata.sha256}`);
  assert.equal(JSON.parse(await shell('cat /var/lib/yanus-backup/offsite.json')).snapshot_epoch, metadata.snapshot_epoch);
  await shell(`rm /var/backups/yanus-db/${id}.acked`);
  receipts.push({ scenario: '14일 지난 ACK 사본만 정리·미전송/최신 보존·복구 시점 퇴행 방지', status: 'PASS' });

  await shell(`printf '\ncorrupt' >> /var/backups/yanus-db/${id}.age`);
  await assert.rejects(shell(`${gateway} ack ${id} ${metadata.sha256}`));
  assert.equal(await shell(`test ! -f /var/backups/yanus-db/${id}.acked && echo preserved`), 'preserved');
  await assert.rejects(shell(`${gateway} archive ../../etc/passwd`));
  receipts.push({ scenario: '손상 archive ACK 및 경로 조작 거절', status: 'PASS' });
  console.log(JSON.stringify({ postgres: 16, scenarios: receipts, cleanup: '컨테이너와 볼륨 정리 예정' }, null, 2));
} finally {
  const result = await run('rm', '-f', '-v', name);
  console.log(JSON.stringify({ cleanup: '컨테이너·볼륨·평문·포트 제거', container: result.stdout.trim() }));
}
