otel.service.name=yanus-backend
otel.resource.attributes=deployment.environment.name=prod,service.instance.id=app-server
otel.traces.exporter=otlp
otel.metrics.exporter=none
otel.logs.exporter=none
otel.exporter.otlp.protocol=http/protobuf
otel.exporter.otlp.endpoint=http://127.0.0.1:4318
otel.exporter.otlp.timeout=2000
otel.bsp.schedule.delay=1000
otel.bsp.max.queue.size=1024
otel.bsp.max.export.batch.size=256
otel.traces.sampler=traceidratio
otel.traces.sampler.arg=0.1
otel.instrumentation.jdbc.query-sanitization.enabled=true
otel.instrumentation.jdbc.experimental.capture-query-parameters=false
otel.instrumentation.jdbc.experimental.sqlcommenter.enabled=false
otel.instrumentation.http.server.capture-request-headers=
otel.instrumentation.http.server.capture-response-headers=
otel.instrumentation.http.client.capture-request-headers=
otel.instrumentation.http.client.capture-response-headers=
otel.instrumentation.logback-mdc.enabled=true
otel.instrumentation.logback-appender.enabled=false
otel.instrumentation.methods.enabled=false
otel.javaagent.logging=simple
