[Service]
ExecStart=
ExecStart=/usr/bin/java -javaagent:/opt/yanus-tracing/opentelemetry-javaagent.jar -Dloader.path=/opt/yanus-tracing/lib -cp /home/yanus/app/app.jar org.springframework.boot.loader.launch.PropertiesLauncher
Environment=OTEL_JAVAAGENT_CONFIGURATION_FILE=/etc/yanus/otel.properties
