[Service]
ExecStart=
ExecStart=/usr/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus/metrics2 --storage.tsdb.retention.time=14d --storage.tsdb.retention.size=2GB --web.listen-address=127.0.0.1:9090
MemoryHigh=384M
MemoryMax=512M
